version: '3.8'

services:
  english-study:
    image: crpi-r8vfvlukq94i69ai.cn-hangzhou.personal.cr.aliyuncs.com/oujy/english-study:v0.0.2
    container_name: english-study
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /root/conf/englishstudy.yaml:/app/config/config.yaml
    ports:
      - "13896:8888"
    networks:
      - postgres        # 连接PostgreSQL网络
      - minio           # 连接MinIO网络
      - englishstudy_network  # 保留原有网络

  english-study-ui:
    image: crpi-r8vfvlukq94i69ai.cn-hangzhou.personal.cr.aliyuncs.com/oujy/english-study-ui:v0.0.1
    container_name: english-study-ui
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "18080:80"
    networks:
      - englishstudy_network  # 仅连接UI专用网络
      - minio                 # 连接MinIO网络

networks:
  # 定义PostgreSQL外部网络
  postgres:
    name: postgres        # 使用之前创建的postgres网络
    external: true        # 标记为外部已存在网络
    
  # 定义MinIO外部网络
  minio:
    name: minio           # 使用之前创建的minio网络
    external: true        # 标记为外部已存在网络
    
  # UI专用网络（内部创建）
  englishstudy_network:
    name: englishstudy
    driver: bridge        # 使用默认桥接驱动